create table cars (
	id BIGSERIAL PRIMARY KEY NOT NULL,
	make VARCHAR(50) NOT NULL,
	model VARCHAR(50) NOT NULL,
	price NUMERIC (20,2) NOT NULL
);
-- D:/Hakimxon/PYTHON/Projects/SQL/lessons/1/cars.sql;
insert into cars (make, model, price) values ('Cadillac', 'Escalade ESV', '7354.37');
insert into cars (make, model, price) values ('Ford', 'Expedition', '7658.94');
insert into cars (make, model, price) values ('Isuzu', 'Stylus', '7983.20');
insert into cars (make, model, price) values ('Acura', 'RL', '6758.28');
insert into cars (make, model, price) values ('BMW', 'Z4', '8448.71');
insert into cars (make, model, price) values ('Toyota', 'Avalon', '3672.32');
insert into cars (make, model, price) values ('Chrysler', 'Sebring', '6477.34');
insert into cars (make, model, price) values ('Mazda', '929', '9295.16');
insert into cars (make, model, price) values ('GMC', 'Yukon XL 1500', '6110.97');
insert into cars (make, model, price) values ('Toyota', 'Tacoma', '8641.61');
insert into cars (make, model, price) values ('Cadillac', 'Seville', '4856.25');
insert into cars (make, model, price) values ('Lexus', 'SC', '9678.38');
insert into cars (make, model, price) values ('Chrysler', 'Cirrus', '6295.24');
insert into cars (make, model, price) values ('Chevrolet', 'Classic', '6808.96');
insert into cars (make, model, price) values ('Infiniti', 'EX', '6123.40');
insert into cars (make, model, price) values ('Cadillac', 'Escalade EXT', '7065.88');
insert into cars (make, model, price) values ('Chrysler', 'Sebring', '3376.51');
insert into cars (make, model, price) values ('Hyundai', 'Genesis Coupe', '4248.77');
insert into cars (make, model, price) values ('Dodge', 'Ram 1500', '3907.16');
insert into cars (make, model, price) values ('Hummer', 'H2', '8799.02');
insert into cars (make, model, price) values ('Pontiac', '1000', '4845.64');
insert into cars (make, model, price) values ('Geo', 'Tracker', '9154.60');
insert into cars (make, model, price) values ('Audi', 'V8', '6153.44');
insert into cars (make, model, price) values ('Nissan', 'NX', '4339.82');
insert into cars (make, model, price) values ('Lotus', 'Elan', '4424.55');
insert into cars (make, model, price) values ('Volkswagen', 'R32', '3888.77');
insert into cars (make, model, price) values ('Jaguar', 'XJ Series', '7870.23');
insert into cars (make, model, price) values ('Land Rover', 'Range Rover', '8489.30');
insert into cars (make, model, price) values ('Isuzu', 'Trooper', '3506.02');
insert into cars (make, model, price) values ('Acura', 'RDX', '3018.24');
insert into cars (make, model, price) values ('Scion', 'xD', '7299.32');
insert into cars (make, model, price) values ('GMC', '3500', '4813.69');
insert into cars (make, model, price) values ('Chevrolet', 'Impala', '6797.70');
insert into cars (make, model, price) values ('Ford', 'F350', '6120.15');
insert into cars (make, model, price) values ('Chevrolet', 'Equinox', '6123.58');
insert into cars (make, model, price) values ('Ford', 'Econoline E150', '7135.41');
insert into cars (make, model, price) values ('Dodge', 'Sprinter', '2059.96');
insert into cars (make, model, price) values ('BMW', '330', '9980.17');
insert into cars (make, model, price) values ('Pontiac', '6000', '2251.71');
insert into cars (make, model, price) values ('Volkswagen', 'Type 2', '8874.70');
insert into cars (make, model, price) values ('Honda', 'Fit', '5047.23');
insert into cars (make, model, price) values ('GMC', 'Sonoma', '7333.86');
insert into cars (make, model, price) values ('Lincoln', 'MKX', '3508.21');
insert into cars (make, model, price) values ('GMC', 'Acadia', '6125.60');
insert into cars (make, model, price) values ('Acura', 'Legend', '8162.84');
insert into cars (make, model, price) values ('Lotus', 'Esprit', '6761.23');
insert into cars (make, model, price) values ('Honda', 'Pilot', '5224.82');
insert into cars (make, model, price) values ('Volkswagen', 'Eos', '8274.44');
insert into cars (make, model, price) values ('Porsche', '928', '2338.60');
insert into cars (make, model, price) values ('Nissan', 'Cube', '2112.90');
insert into cars (make, model, price) values ('Toyota', 'Supra', '4882.78');
insert into cars (make, model, price) values ('Jeep', 'Grand Cherokee', '3935.05');
insert into cars (make, model, price) values ('Lincoln', 'MKX', '8683.20');
insert into cars (make, model, price) values ('Toyota', 'Celica', '5226.84');
insert into cars (make, model, price) values ('Volkswagen', 'Passat', '9006.77');
insert into cars (make, model, price) values ('Volvo', 'S80', '5296.11');
insert into cars (make, model, price) values ('MINI', 'Cooper Clubman', '4977.60');
insert into cars (make, model, price) values ('Suzuki', 'Daewoo Lacetti', '3800.76');
insert into cars (make, model, price) values ('Volkswagen', 'New Beetle', '2826.47');
insert into cars (make, model, price) values ('Lamborghini', 'Murciélago', '7510.77');
insert into cars (make, model, price) values ('Dodge', 'Ram Van 1500', '2496.56');
insert into cars (make, model, price) values ('Dodge', 'Grand Caravan', '8897.53');
insert into cars (make, model, price) values ('Cadillac', 'XLR', '5416.14');
insert into cars (make, model, price) values ('Aptera', 'Type-1h', '8843.05');
insert into cars (make, model, price) values ('Pontiac', 'Bonneville', '5448.09');
insert into cars (make, model, price) values ('Buick', 'Hearse', '2930.87');
insert into cars (make, model, price) values ('Acura', 'CL', '2599.00');
insert into cars (make, model, price) values ('Mitsubishi', 'Excel', '6367.85');
insert into cars (make, model, price) values ('Land Rover', 'Range Rover', '6218.17');
insert into cars (make, model, price) values ('Hyundai', 'Tiburon', '5839.83');
insert into cars (make, model, price) values ('Kia', 'Rondo', '4507.21');
insert into cars (make, model, price) values ('Honda', 'Civic', '4051.75');
insert into cars (make, model, price) values ('Acura', 'RL', '7904.38');
insert into cars (make, model, price) values ('Lincoln', 'Navigator L', '9763.62');
insert into cars (make, model, price) values ('Dodge', 'Ram', '2513.17');
insert into cars (make, model, price) values ('Scion', 'xB', '7732.53');
insert into cars (make, model, price) values ('Pontiac', 'G6', '8311.58');
insert into cars (make, model, price) values ('Honda', 'S2000', '6699.11');
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', '2392.84');
insert into cars (make, model, price) values ('Chevrolet', 'Express 3500', '5593.47');
insert into cars (make, model, price) values ('Lexus', 'LS', '7385.23');
insert into cars (make, model, price) values ('Mazda', 'Mazda6', '9171.66');
insert into cars (make, model, price) values ('Audi', 'TT', '9471.86');
insert into cars (make, model, price) values ('GMC', 'Terrain', '2907.99');
insert into cars (make, model, price) values ('Nissan', 'Titan', '9445.53');
insert into cars (make, model, price) values ('GMC', 'Savana 3500', '7984.87');
insert into cars (make, model, price) values ('Toyota', 'Echo', '8739.26');
insert into cars (make, model, price) values ('Plymouth', 'Roadrunner', '4214.11');
insert into cars (make, model, price) values ('Volkswagen', 'R32', '2027.75');
insert into cars (make, model, price) values ('Chevrolet', 'Lumina', '5688.27');
insert into cars (make, model, price) values ('Mercedes-Benz', 'S-Class', '7397.53');
insert into cars (make, model, price) values ('Ford', 'Tempo', '6561.16');
insert into cars (make, model, price) values ('Chevrolet', 'Cavalier', '6084.74');
insert into cars (make, model, price) values ('Hummer', 'H3T', '9338.12');
insert into cars (make, model, price) values ('Mitsubishi', 'Montero Sport', '4302.14');
insert into cars (make, model, price) values ('Dodge', 'Dakota', '9399.00');
insert into cars (make, model, price) values ('Buick', 'Park Avenue', '5748.18');
insert into cars (make, model, price) values ('Lincoln', 'Continental', '4648.29');
insert into cars (make, model, price) values ('Kia', 'Forte', '2285.53');
insert into cars (make, model, price) values ('Ford', 'Freestar', '3027.44');
insert into cars (make, model, price) values ('Volvo', 'S80', '3409.28');
insert into cars (make, model, price) values ('Saab', '9-2X', '2744.98');
insert into cars (make, model, price) values ('BMW', 'M3', '5054.03');
insert into cars (make, model, price) values ('Maserati', 'Quattroporte', '9691.95');
insert into cars (make, model, price) values ('Mercedes-Benz', '300SL', '4010.69');
insert into cars (make, model, price) values ('Chevrolet', 'Express 1500', '9521.09');
insert into cars (make, model, price) values ('Toyota', 'Corolla', '5466.04');
insert into cars (make, model, price) values ('Lincoln', 'Town Car', '5985.73');
insert into cars (make, model, price) values ('Land Rover', 'LR2', '9086.82');
insert into cars (make, model, price) values ('Lotus', 'Evora', '4045.63');
insert into cars (make, model, price) values ('Volkswagen', 'CC', '3665.64');
insert into cars (make, model, price) values ('Lexus', 'RX', '3455.92');
insert into cars (make, model, price) values ('Honda', 'Civic', '4002.40');
insert into cars (make, model, price) values ('GMC', 'Savana 2500', '8092.51');
insert into cars (make, model, price) values ('Chrysler', 'Sebring', '6874.85');
insert into cars (make, model, price) values ('Chevrolet', 'Cavalier', '9097.36');
insert into cars (make, model, price) values ('Mazda', 'B-Series Plus', '9597.52');
insert into cars (make, model, price) values ('Morgan', 'Aero 8', '5594.92');
insert into cars (make, model, price) values ('Dodge', 'D250', '8968.35');
insert into cars (make, model, price) values ('Mitsubishi', 'Galant', '3107.74');
insert into cars (make, model, price) values ('GMC', 'Vandura 2500', '8117.02');
insert into cars (make, model, price) values ('Subaru', 'B9 Tribeca', '4973.83');
insert into cars (make, model, price) values ('Hyundai', 'Sonata', '2345.85');
insert into cars (make, model, price) values ('Volvo', 'C70', '7400.09');
insert into cars (make, model, price) values ('Honda', 'Ridgeline', '8982.02');
insert into cars (make, model, price) values ('Mazda', 'MX-3', '3044.96');
insert into cars (make, model, price) values ('Dodge', 'Grand Caravan', '3062.21');
insert into cars (make, model, price) values ('Volvo', 'XC90', '8877.21');
insert into cars (make, model, price) values ('Lexus', 'SC', '7490.74');
insert into cars (make, model, price) values ('Mazda', 'RX-8', '5119.02');
insert into cars (make, model, price) values ('Chevrolet', 'Lumina', '4101.29');
insert into cars (make, model, price) values ('Mercury', 'Sable', '4225.47');
insert into cars (make, model, price) values ('Mazda', 'CX-7', '5140.45');
insert into cars (make, model, price) values ('Toyota', 'Avalon', '7083.76');
insert into cars (make, model, price) values ('Chrysler', '300', '7122.54');
insert into cars (make, model, price) values ('Oldsmobile', 'Intrigue', '6993.45');
insert into cars (make, model, price) values ('Volkswagen', 'Passat', '5685.70');
insert into cars (make, model, price) values ('Infiniti', 'I', '8655.44');
insert into cars (make, model, price) values ('Chevrolet', 'Suburban 2500', '5450.97');
insert into cars (make, model, price) values ('Dodge', 'Dakota Club', '7589.79');
insert into cars (make, model, price) values ('Lotus', 'Exige', '2742.07');
insert into cars (make, model, price) values ('BMW', '760', '3668.57');
insert into cars (make, model, price) values ('GMC', 'Yukon XL 1500', '3851.43');
insert into cars (make, model, price) values ('Lexus', 'LS', '8467.04');
insert into cars (make, model, price) values ('Buick', 'Park Avenue', '7172.35');
insert into cars (make, model, price) values ('Chevrolet', 'Cavalier', '3992.78');
insert into cars (make, model, price) values ('Cadillac', 'STS', '6538.00');
insert into cars (make, model, price) values ('Chevrolet', 'Suburban 2500', '9717.26');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SL-Class', '5903.09');
insert into cars (make, model, price) values ('Volkswagen', 'GTI', '4205.96');
insert into cars (make, model, price) values ('Honda', 'CR-Z', '4732.57');
insert into cars (make, model, price) values ('Dodge', 'Dakota', '9917.96');
insert into cars (make, model, price) values ('Pontiac', 'Bonneville', '5024.68');
insert into cars (make, model, price) values ('Audi', 'A8', '7350.02');
insert into cars (make, model, price) values ('Eagle', 'Summit', '3235.75');
insert into cars (make, model, price) values ('Chevrolet', 'Silverado', '5352.38');
insert into cars (make, model, price) values ('Maybach', '62', '6892.34');
insert into cars (make, model, price) values ('Hummer', 'H1', '3243.60');
insert into cars (make, model, price) values ('Dodge', 'Viper RT/10', '5823.71');
insert into cars (make, model, price) values ('Chrysler', 'Pacifica', '8255.43');
insert into cars (make, model, price) values ('Mercedes-Benz', 'SL-Class', '7958.50');
insert into cars (make, model, price) values ('GMC', 'Sonoma Club', '3823.09');
insert into cars (make, model, price) values ('Mitsubishi', 'Eclipse', '4649.63');
insert into cars (make, model, price) values ('GMC', 'Sierra 3500', '4803.79');
insert into cars (make, model, price) values ('Honda', 'CR-V', '2002.05');
insert into cars (make, model, price) values ('GMC', 'Savana 2500', '6694.51');
insert into cars (make, model, price) values ('Aston Martin', 'DBS', '9224.57');
insert into cars (make, model, price) values ('Chevrolet', 'Suburban 1500', '3252.98');
insert into cars (make, model, price) values ('Pontiac', 'Sunbird', '7862.60');
insert into cars (make, model, price) values ('Volvo', 'XC90', '3823.81');
insert into cars (make, model, price) values ('Toyota', 'Celica', '3628.33');
insert into cars (make, model, price) values ('Ford', 'Aspire', '9567.56');
insert into cars (make, model, price) values ('Ford', 'Tempo', '8318.80');
insert into cars (make, model, price) values ('Bentley', 'Continental Flying Spur', '3958.88');
insert into cars (make, model, price) values ('Chevrolet', 'Blazer', '8747.54');
insert into cars (make, model, price) values ('Lotus', 'Exige', '6197.17');
insert into cars (make, model, price) values ('Chevrolet', 'Express', '6855.96');
insert into cars (make, model, price) values ('Mitsubishi', 'Starion', '3442.35');
insert into cars (make, model, price) values ('Honda', 'Fit', '7411.84');
insert into cars (make, model, price) values ('Mercury', 'Mountaineer', '4026.51');
insert into cars (make, model, price) values ('Saturn', 'Sky', '4859.23');
insert into cars (make, model, price) values ('Toyota', 'Tacoma', '7857.75');
insert into cars (make, model, price) values ('Pontiac', 'Tempest', '7032.57');
insert into cars (make, model, price) values ('Jeep', 'Grand Cherokee', '7302.05');
insert into cars (make, model, price) values ('Mercedes-Benz', 'CLK-Class', '8925.23');
insert into cars (make, model, price) values ('Ford', 'F250', '6761.43');
insert into cars (make, model, price) values ('Mazda', 'MPV', '8906.15');
insert into cars (make, model, price) values ('Ford', 'E-Series', '3583.78');
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', '3500.55');
insert into cars (make, model, price) values ('GMC', 'Savana 1500', '5550.89');
insert into cars (make, model, price) values ('Dodge', 'Dakota', '8667.74');
insert into cars (make, model, price) values ('Chevrolet', 'Venture', '4132.68');
insert into cars (make, model, price) values ('MINI', 'Cooper', '6484.24');
insert into cars (make, model, price) values ('Chevrolet', 'Suburban 1500', '8378.35');
insert into cars (make, model, price) values ('Hummer', 'H1', '8267.62');
insert into cars (make, model, price) values ('Suzuki', 'Vitara', '8059.90');
insert into cars (make, model, price) values ('Kia', 'Rondo', '6520.52');
insert into cars (make, model, price) values ('GMC', 'Sierra 2500', '9678.91');
insert into cars (make, model, price) values ('Infiniti', 'M', '8417.38');
insert into cars (make, model, price) values ('Hyundai', 'Elantra', '3311.26');
insert into cars (make, model, price) values ('Suzuki', 'Grand Vitara', '7303.39');
insert into cars (make, model, price) values ('Mercedes-Benz', '300SL', '9409.48');
insert into cars (make, model, price) values ('Volvo', 'S40', '3723.63');
insert into cars (make, model, price) values ('Land Rover', 'Freelander', '7355.21');
insert into cars (make, model, price) values ('Chevrolet', 'Cavalier', '2935.87');
insert into cars (make, model, price) values ('Oldsmobile', 'Ciera', '8899.04');
insert into cars (make, model, price) values ('Jeep', 'Wrangler', '3293.77');
insert into cars (make, model, price) values ('GMC', 'Savana 1500', '2712.42');
insert into cars (make, model, price) values ('Ford', 'Club Wagon', '2319.46');
insert into cars (make, model, price) values ('Chrysler', 'Concorde', '9331.50');
insert into cars (make, model, price) values ('Dodge', 'Monaco', '9112.79');
insert into cars (make, model, price) values ('Honda', 'Ridgeline', '5268.04');
insert into cars (make, model, price) values ('Mitsubishi', 'i-MiEV', '5498.60');
insert into cars (make, model, price) values ('Lexus', 'SC', '6809.96');
insert into cars (make, model, price) values ('Ferrari', '612 Scaglietti', '2399.11');
insert into cars (make, model, price) values ('Saab', '9-7X', '7068.81');
insert into cars (make, model, price) values ('Scion', 'xD', '5488.98');
insert into cars (make, model, price) values ('Bentley', 'Continental Super', '5538.07');
insert into cars (make, model, price) values ('Honda', 'Accord', '8295.18');
insert into cars (make, model, price) values ('Suzuki', 'Samurai', '9282.32');
insert into cars (make, model, price) values ('Dodge', 'Ram 3500 Club', '6645.56');
insert into cars (make, model, price) values ('Maybach', '57', '3987.44');
insert into cars (make, model, price) values ('Volvo', 'C70', '9095.75');
insert into cars (make, model, price) values ('Mercedes-Benz', 'GL-Class', '8510.91');
insert into cars (make, model, price) values ('Lexus', 'RX', '4828.41');
insert into cars (make, model, price) values ('Ferrari', '599 GTB Fiorano', '7429.04');
insert into cars (make, model, price) values ('Mazda', 'RX-7', '7116.70');
insert into cars (make, model, price) values ('Jeep', 'Patriot', '9497.73');
insert into cars (make, model, price) values ('Infiniti', 'M', '4545.78');
insert into cars (make, model, price) values ('Honda', 'Pilot', '3179.99');
insert into cars (make, model, price) values ('Mercury', 'Cougar', '6042.19');
insert into cars (make, model, price) values ('Aston Martin', 'DB9', '5993.20');
insert into cars (make, model, price) values ('Cadillac', 'Fleetwood', '3344.05');
insert into cars (make, model, price) values ('Infiniti', 'Q', '7328.25');
insert into cars (make, model, price) values ('Toyota', 'Celica', '4347.80');
insert into cars (make, model, price) values ('Scion', 'tC', '3554.00');
insert into cars (make, model, price) values ('Ford', 'Tempo', '9449.82');
insert into cars (make, model, price) values ('Dodge', 'Charger', '8991.68');
insert into cars (make, model, price) values ('Suzuki', 'Daewoo Lacetti', '5450.98');
insert into cars (make, model, price) values ('Toyota', 'Land Cruiser', '4254.37');
insert into cars (make, model, price) values ('Porsche', 'Cayenne', '2210.71');
insert into cars (make, model, price) values ('Land Rover', 'Defender 110', '3978.98');
insert into cars (make, model, price) values ('Ford', 'Thunderbird', '6576.55');
insert into cars (make, model, price) values ('Honda', 'Odyssey', '4307.23');
insert into cars (make, model, price) values ('Nissan', '240SX', '2380.82');
insert into cars (make, model, price) values ('Nissan', 'Pathfinder', '8648.69');
insert into cars (make, model, price) values ('Cadillac', 'SRX', '8948.76');
insert into cars (make, model, price) values ('Cadillac', 'Brougham', '8417.71');
insert into cars (make, model, price) values ('Infiniti', 'FX', '6558.08');
insert into cars (make, model, price) values ('Pontiac', 'Grand Prix', '8550.46');
insert into cars (make, model, price) values ('Cadillac', 'Escalade ESV', '4142.72');
insert into cars (make, model, price) values ('Pontiac', 'Sunbird', '6187.99');
insert into cars (make, model, price) values ('Acura', 'MDX', '7280.23');
insert into cars (make, model, price) values ('Ford', 'Expedition EL', '7615.29');
insert into cars (make, model, price) values ('Buick', 'Century', '7400.99');
insert into cars (make, model, price) values ('Ford', 'F150', '5916.98');
insert into cars (make, model, price) values ('Chevrolet', 'Colorado', '7202.84');
insert into cars (make, model, price) values ('Porsche', 'Cayenne', '5696.33');
insert into cars (make, model, price) values ('Audi', 'S6', '4796.44');
insert into cars (make, model, price) values ('Dodge', 'Neon', '6445.16');
insert into cars (make, model, price) values ('Saab', '900', '5522.73');
insert into cars (make, model, price) values ('Chevrolet', 'Silverado 2500', '2022.92');
insert into cars (make, model, price) values ('Pontiac', 'Bonneville', '5724.67');
insert into cars (make, model, price) values ('Subaru', 'Legacy', '4334.66');
insert into cars (make, model, price) values ('Suzuki', 'Equator', '5303.87');
insert into cars (make, model, price) values ('Subaru', 'Impreza', '8605.55');
insert into cars (make, model, price) values ('Acura', 'NSX', '6676.61');
insert into cars (make, model, price) values ('Volkswagen', 'GTI', '6028.97');
insert into cars (make, model, price) values ('Honda', 'Odyssey', '3039.11');
insert into cars (make, model, price) values ('Mitsubishi', 'Galant', '7299.69');
insert into cars (make, model, price) values ('Chevrolet', 'Corvette', '4868.49');
insert into cars (make, model, price) values ('Nissan', 'Xterra', '9600.73');
insert into cars (make, model, price) values ('Subaru', 'Impreza', '9848.04');
insert into cars (make, model, price) values ('Chevrolet', 'Express 1500', '5331.73');
insert into cars (make, model, price) values ('Dodge', 'Ram Van 3500', '8993.99');
insert into cars (make, model, price) values ('Mercury', 'Mariner', '3988.61');
insert into cars (make, model, price) values ('Mazda', 'Mazda6 5-Door', '6322.76');
insert into cars (make, model, price) values ('Chevrolet', 'Lumina', '4640.38');
insert into cars (make, model, price) values ('Cadillac', 'Escalade EXT', '8523.33');
insert into cars (make, model, price) values ('Toyota', 'MR2', '7776.49');
insert into cars (make, model, price) values ('Acura', 'TL', '3877.00');
insert into cars (make, model, price) values ('Toyota', 'Corolla', '6579.50');
insert into cars (make, model, price) values ('Porsche', '928', '6319.67');
insert into cars (make, model, price) values ('Ford', 'E-350 Super Duty Van', '7291.57');
insert into cars (make, model, price) values ('Buick', 'LaCrosse', '3904.93');
insert into cars (make, model, price) values ('Volkswagen', 'Touareg', '9795.99');
insert into cars (make, model, price) values ('Nissan', 'Maxima', '7515.84');
insert into cars (make, model, price) values ('Lincoln', 'Town Car', '4007.37');
insert into cars (make, model, price) values ('Acura', 'NSX', '3627.70');
insert into cars (make, model, price) values ('Cadillac', 'Escalade ESV', '7491.13');
insert into cars (make, model, price) values ('Cadillac', 'XLR', '4598.96');
insert into cars (make, model, price) values ('Dodge', 'Dakota', '3072.09');
insert into cars (make, model, price) values ('Acura', 'RDX', '8686.94');
insert into cars (make, model, price) values ('Ford', 'Aerostar', '6642.67');
insert into cars (make, model, price) values ('Ford', 'LTD Crown Victoria', '4899.15');
insert into cars (make, model, price) values ('Audi', '80', '6622.89');
insert into cars (make, model, price) values ('Mitsubishi', 'Challenger', '8579.60');
insert into cars (make, model, price) values ('Mazda', 'RX-8', '2889.76');
insert into cars (make, model, price) values ('Volkswagen', 'Jetta', '4011.77');
insert into cars (make, model, price) values ('Subaru', 'SVX', '7419.57');
